### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by engcn** [trzsz/trzsz-go#1]
如果不用apt install安装, 在Ubuntu上使用源码编译安装，如何操作?

**Comment by lonnywong** [comment]
```sh
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
make
sudo make install
```

**Comment by engcn** [comment]
go版本最低多少？

**Comment by engcn** [comment]
客户端go版编译安装成功了，服务端和python版的trz冲突吗？还是需要服务也需要装go版的trzsz?

**Comment by lonnywong** [comment]
我还没有测过 go 最低版本支持多少，我本地用的是 1.18 的。

`Python`、`JavaScript` 和 `Go` 的 trzsz 是完全兼容的，下表打勾的是已实现的。

|  | Python | JavaScript | Go |
| :----- | :-----: | :-----: | :-----: |
| 服务端 trz / tsz | √ | | |
| 客户端 trzsz | √ | √ | |

注意，Go 的客户端还没写完，集成 trzsz 的功能还在开发中。

**Comment by engcn** [comment]
ok,谢谢

**Comment by lonnywong** [comment]
@engcn 基本功能已写完。

不过我还没有完全测试，预计测试时间会比较久，你可以先试用下，遇到问题可以提 issue。

PS：windows 平台多了个 `\r`，未解决。

**Comment by engcn** [comment]
在Ubuntu20.04.4默认终端上测试下载文件，
[root@teng ~]# tsz Melody.mp3 
::TRZSZGO:TRANSFER:S:1.0.0:0
等了好几秒才输出进度条，进度条刷新间隔大概5~6秒吧,如下图：
![Peek](https://user-images.githubusercontent.com/26758766/169696191-352ed070-02b0-4371-95ea-e0d1183a470a.gif)

**Comment by lonnywong** [comment]
> 

这个问题已经优化了，在 1.0.1 版本，不过我还没发布。在等 iTerm2 的作者先发布一个依赖包，等了半个多月了，呵~

你可以先试试安装测试的版本（ 服务端的版本不依赖 iTerm2 的 ）：

1、卸载正式版
```sh
sudo python3 -m pip uninstall trzsz-libs trzsz-svr trzsz
```

2、安装测试版
```sh
sudo python3 -m pip install --upgrade -i https://test.pypi.org/simple/ trzsz==0.2.110
```

**Comment by engcn** [comment]
恩，这个trzsz==0.2.110测试正常，非常感谢
上边的表格， “Python、JavaScript 和 Go 的 trzsz 是完全兼容的，下表打勾的是已实现的”，建议加到readme里.

**Comment by engcn** [comment]
trzsz tmux之后，在tmux的pane中，ssh到远程主机是不是就可以不用trzsz, 也可以上传下载文件了?

**Comment by lonnywong** [comment]
> 在Ubuntu20.04.4默认终端上测试下载文件，

trzsz 只需要运行一次，但是直接 `trzsz tmux` 就是 tmux 进程运行在本地，还有些问题未解决。

但是，先运行 `tmux` （ 不需要 trzsz ），再 `trzsz ssh` 到远程，应该是可以的。

为了使用方便，可以在本地设置个  alias ，例如 `alias ssh="trzsz ssh"`。

**Comment by engcn** [comment]
哈哈，好巧啊，我正在设置 alias

**Comment by engcn** [comment]
在局域网离线环境下，不太方便在服务端安装python版trzsz，问下 trzsz-go版的trz, tsz两个命令后续是否会独立支持？

**Comment by lonnywong** [comment]
> 在局域网离线环境下，不太方便在服务端安装python版trzsz，问下 trzsz-go版的trz, tsz两个命令后续是否会独立支持？

会写的，但是估计要比较久之后才有时间搞。

**Comment by engcn** [comment]
哦，那太好了很期待; 这样离线环境下只需要安装 trzsz-go了.

**Comment by lonnywong** [comment]
go 版的 `trz` 和 `tsz` 已发布，版本 `v0.1.5` 。
