### ISSUE TITLE
能否实现rsync增量上传呢？

### ISSUE THREAD

**Issue by taolive** [trzsz/trzsz-go#10]
能否实现rsync命令的增量上传呢？

**Comment by lonnywong** [comment]
理论上是可行的，传文件内容之前先判断一下文件是否存在，若存在的则再看 md5 是否一致，md5 也一致就可以跳过这个文件。

我后面有空时实现一下。

**Comment by lonnywong** [comment]
计划：当使用 `-y` 覆盖上传或下载时，新版本自动切换到增量传输的模式，跳过前面文件内容一致的部分，追加剩余的文件内容。
如果上一次传输过程中发生了中断，再一次使用 `-y` 选项传输时，则类似于断点续传的功能。
如果 `-y` 发现要传的文件完全一致，则校验 md5 一致就直接完成。

**Comment by lonnywong** [comment]
`v1.1.4` 已实现类似 rsync 的效果。

如果发生中断，或者传完后文件有修改，再使用 `trz -y` 上传，或者使用 `tsz -y xxx` 下载， 将会快速跳过前面一致的部分，从不一致的位置开始断点续传。
