### ISSUE TITLE
Windows 下 vim 工作不正常

### ISSUE THREAD

**Issue by hulucc** [trzsz/trzsz-go#13]
1. 打开 `cmd.exe`, 并执行 `trzsz vim.exe --clean`
2. 按 `i` 切换到输入模式，随意输入一些字符
期望：符合vim正常功能
实际：vim命令行处错位
```
$ vim --version
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul  3 2022 22:05:02)
MS-Windows 64-bit console version
Included patches: 1-32
Compiled by appveyor@APPVYR-WIN
```
```
OS Version:                10.0.19044 N/A Build 19044
```

**Comment by lonnywong** [comment]
直接执行 `vim.exe --clean` 是否正常的？

如果是 `trzsz cmd` 之后，再执行 `vim.exe --clean` 又如何？

**Comment by hulucc** [comment]
> 直接执行 `vim.exe --clean` 是否正常的？
> 
> 如果是 `trzsz cmd` 之后，再执行 `vim.exe --clean` 又如何？

直接执行 `vim.exe --clean` 正常
`trzsz cmd` 之后，再执行 `vim.exe --clean` 不正常，与执行 `trzsz vim.exe --clean`一致

**Comment by lonnywong** [comment]
OK，我抽空研究下怎么解决。

**Comment by lonnywong** [comment]
@hulucc 我在 cmd 中用 vim 可能没遇到你的问题，不过我在搜索时确实是显示错位了。

最新的代码已修复 vim 搜索时显示错位的问题，你试试看有没有一并解决了你遇到的问题？

可以自己编译一个：
```sh
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
GOOS=windows go build ./cmd/trzsz
```
`trzsz.exe` 就在当前 trzsz-go 目录下。

**Comment by hulucc** [comment]
最新版本中确认已修复

**Comment by lonnywong** [comment]
@hulucc 感谢反馈。
