### ISSUE TITLE
使用过 tsz 或 trz 后，再用vi编辑文件，会导致再弹出一次接收

### ISSUE THREAD

**Issue by fengqi** [trzsz/trzsz-go#17]
环境是 windows 10 terminal，远程是 ubuntu 20.04

tsz xx 接受后
vi xx :q退出就会弹出接收文件，
如果取消，终端会输出一串 #ACT 开头的base64类似的字符
如果接受，文件会正常接收，产生一个.1结尾的新文件，且终端卡住，ctrl+c后，终端输出 #fail开头的base64类似的字符
![微信截图_20220808200300](https://user-images.githubusercontent.com/517708/183413725-6290a3b0-cca1-4e16-b8cf-aa1e251eb5f5.png)

**Comment by lonnywong** [comment]
我也遇到过类似的问题，上传或下载完之后，`clear` 一下应该可以临时解决。

是 Windows 会刷新整个屏幕（ 重复输出 ::TRZSZ:TRANSFER:0.1.9:0 那个字符串 ）导致的，我再想想看有没有好的办法解决。

**Comment by fengqi** [comment]
clear 有用

**Comment by lonnywong** [comment]
@fengqi 可以用最新的代码编译试试，按理说不需要 clear 也不会重复弹出的了。
```sh
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
GOOS=windows go build ./cmd/trzsz
GOOS=linux go build ./cmd/trz
GOOS=linux go build ./cmd/tsz
```
编译出来的结果就在当前目录。

**Comment by fengqi** [comment]
我试试看

**Comment by lonnywong** [comment]
> 我试试看

结果如何，还会重复弹出不？

**Comment by fengqi** [comment]
> > 我试试看
> 
> 结果如何，还会重复弹出不？

不会了

**Comment by lonnywong** [comment]
感谢反馈
