### ISSUE TITLE
使用trz上传文件速度很慢

### ISSUE THREAD

**Issue by bigruid** [trzsz/trzsz-go#18]
![image](https://user-images.githubusercontent.com/40227796/190547889-281dc773-2b00-49ba-a48b-13862e30e50a.png)
![image](https://user-images.githubusercontent.com/40227796/190548621-34032ae9-2de1-494b-9db6-0ab6150d1bdc.png)
![image](https://user-images.githubusercontent.com/40227796/190548671-4969434e-728f-4595-8790-8cd8d4b38154.png)

trzsz go 0.1.9，系统是windows11 22h2 10.0.22622.598，使用cmd或者powershell 都会出现trz速度极慢的问题，相同主机及文件，tsz速度正常，rz的速度也是正常的

**Comment by lonnywong** [comment]
只要经过了 Windows ，trz 是很慢，目前还没找到解决办法。

你说 rz 的速度是正常的，请问是如何使用 rz 的？我看能不能借助他找出解决办法。

如果你是用 xshell、SecureCRT 等直接登录 Linux 的 （ 中间不打开 cmd 或 PowerShell 的 ），那是正常的。
trz 也可以做到，使用 tabby 或 electerm 终端的上传速度是正常的（ 注意不要打开 cmd 或 PowerShell 再 ssh 到 Linux，要直接登录 Linux ）。

**Comment by bigruid** [comment]
> 只要经过了 Windows ，trz 是很慢，目前还没找到解决办法。
> 
> 你说 rz 的速度是正常的，请问是如何使用 rz 的？我看能不能借助他找出解决办法。
> 
> 如果你是用 xshell、SecureCRT 等直接登录 Linux 的 （ 中间不打开 cmd 或 PowerShell 的 ），那是正常的。 trz 也可以做到，使用 tabby 或 electerm 终端的上传速度是正常的（ 注意不要打开 cmd 或 PowerShell 再 ssh 到 Linux，要直接登录 Linux ）。

了解了，rz是通过SecureCRT 登录测试的

**Comment by yxing-xyz** [comment]
> 只要经过了 Windows ，trz 是很慢，目前还没找到解决办法。
> 
> 你说 rz 的速度是正常的，请问是如何使用 rz 的？我看能不能借助他找出解决办法。
> 
> 如果你是用 xshell、SecureCRT 等直接登录 Linux 的 （ 中间不打开 cmd 或 PowerShell 的 ），那是正常的。 trz 也可以做到，使用 tabby 或 electerm 终端的上传速度是正常的（ 注意不要打开 cmd 或 PowerShell 再 ssh 到 Linux，要直接登录 Linux ）。

mac下的zssh用rz也很慢，不知道为啥， windows的trz为啥很慢啊，帮忙解释下

**Comment by lonnywong** [comment]
> 
> mac下的zssh用rz也很慢，不知道为啥， windows的trz为啥很慢啊，帮忙解释下

可以看看这个 https://github.com/trzsz/trzsz-go/issues/21#issuecomment-1441664213 ，我也不确定是不是真的是这原因。

**Comment by lonnywong** [comment]
可以用 https://github.com/trzsz/trzsz-ssh 试试，解决了 Windows 使用 `trzsz ssh` 上传慢的问题。

tssh 是写给我自己用的工具，功能还不是很完善。

**Comment by FinallyFinancialFreedom** [comment]
顺带提，windows terminal下用tssh，trz的速度不到1M，如果rz应该可以打满网络带宽。不过我很少传大文件，这个问题不明显。

**Comment by lonnywong** [comment]
> 顺带提，windows terminal下用tssh，trz的速度不到1M，如果rz应该可以打满网络带宽。不过我很少传大文件，这个问题不明显。

tssh -v 看看用的是不是最新的？另外 time trz 和 time rz 上传同样的文件，分别看看耗时多少？

**Comment by FinallyFinancialFreedom** [comment]
> > 顺带提，windows terminal下用tssh，trz的速度不到1M，如果rz应该可以打满网络带宽。不过我很少传大文件，这个问题不明显。
> 
> tssh -v 看看用的是不是最新的？另外 time trz 和 time rz 上传同样的文件，分别看看耗时多少？

tssh刚更新的最新的0.1.5，time trz包括了选文件的时间，不太准，看速度就是1MB上下，耗时比较长；rz的话20多MB，差距明显。不过tsz速度非常快，跟sz不相上下。
