### ISSUE TITLE
windows下能否支持git bash终端?

### ISSUE THREAD

**Issue by engcn** [trzsz/trzsz-go#2]
![图片](https://user-images.githubusercontent.com/26758766/170156080-e2e39179-3261-49fc-8c2a-bb5f41bb4f8d.png)

**Comment by lonnywong** [comment]
这样可以用：
1、在前面再加一个 `winpty`
2、使用 Windows 自带的 `ssh`
如：
```
 winpty trzsz /c/Windows/System32/OpenSSH/ssh.exe x.x.x.x
```

使用 msys 或 cygwin 的那个 ssh 总是会在输入时漏数据，还没找出原因。
即使只加上 `winpty` ，如 `winpty ssh x.x.x.x`，在粘贴大量数据时也会漏数据，因此应该不是 `trzsz` 的问题。

**Comment by engcn** [comment]
![image](https://user-images.githubusercontent.com/26758766/170828331-05d8cd96-2f3b-47ce-8a88-bbb52014ab6a.png)

**Comment by lonnywong** [comment]
你漏了 trzsz 啦

**Comment by engcn** [comment]
加上trzsz之后，有弹框，然后没反应
![image](https://user-images.githubusercontent.com/26758766/170828968-2f52d057-84db-4fb9-8966-b56bc9cef5dc.png)

**Comment by lonnywong** [comment]
哦，忘了说了，需要在服务端安装 trzsz 测试版 `0.2.111` 。

1、卸载正式版
```
sudo python3 -m pip uninstall trzsz-libs trzsz-svr trzsz
```
2、安装测试版
```
sudo python3 -m pip install --upgrade -i https://test.pypi.org/simple/ trzsz==0.2.111
```

**Comment by engcn** [comment]
可以了，谢谢
