### ISSUE TITLE
bug终端自动卡死

### ISSUE THREAD

**Issue by 871690991** [trzsz/trzsz-go#20]
登录服务器后 服务器自动断开连接或者电脑断网这个终端ssh不会退出，就hang死在那除非重启这个终端。

**Comment by lonnywong** [comment]
如果直接 ssh 是什么样的表现？ 

trzsz 进程只是拉起了一个 ssh 子进程，当 ssh 子进程退出时，trzsz 进程会自动退出的。

也可以在挂起的时候，在本地另一个终端看看 ssh 子进程还在不在？

**Comment by 871690991** [comment]
![image](https://user-images.githubusercontent.com/35527325/223604769-514990cf-8cfd-4c52-ab88-2d2c0509a51b.png)
这个报错是trzsz提示的么  怀疑服务器连接超时时候trzsz导致ssh子进程很久以后才能自动超时退出
