### ISSUE TITLE
kubernetes pod中可以下载上传文件吗

### ISSUE THREAD

**Issue by mvpbang** [trzsz/trzsz-go#22]
疑问，测试发现不行的

**Comment by lonnywong** [comment]
可以详细讲讲是怎么登录到 pod 里面的？`trz / tsz` 命令后没有弹出文件选译对话框，还是提示什么错误？

**Comment by ffxgamer** [comment]
> mvpbang

今天试了下, 是可以使用的, 进到pod里, 然后直接wget下载的trzsz的binary包,解压到/usr/local/bin/目录下.
然后iterm2里照着文档配置了一下, 使用上完全ok.

Today I tried it out and it worked. I entered the pod and used wget to download the binary package of trzsz, then I extracted it to the /usr/local/bin/ directory. After configuring it according to the documentation in iTerm2, it worked perfectly.
