### ISSUE TITLE
xshell 7  不弹出窗口

### ISSUE THREAD

**Issue by jhsswl** [trzsz/trzsz-go#24]
xshell 7 软件，登录rocky 8.5系统，yum安装trzsz，使用trz不会弹出窗口，拖拽文件也不行。

**Comment by lonnywong** [comment]
xshell 需要 xshell 的公司支持才可以。

用 xshell 的本地 shell ，然后 trzsz ssh 登录，勉强可用，可参考 https://github.com/trzsz/trzsz/issues/18#issuecomment-1157239528

**Comment by lonnywong** [comment]
@jhsswl 可以试试 https://github.com/trzsz/trzsz-ssh
在 xshell 中打开一个本地 shell，然后用 tssh 登录服务器，就可以用 trz / tsz 上传和下载了。
