### ISSUE TITLE
can not start ssh under windows

### ISSUE THREAD

**Issue by cdgh2021** [trzsz/trzsz-go#25]
OS: Windows 11

got this error:

C:\Users\xxx>trzsz ssh user@xxx
Failed to create console process: The system cannot find the file specified.

C:\Users\xxx>ssh -V
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3

**Comment by lonnywong** [comment]
* If using [MSYS2](https://www.msys2.org/) or [Git Bash](https://www.atlassian.com/git/tutorials/git-bash) on windows, and getting an error `The handle is invalid`.
  * Install [winpty](https://github.com/rprichard/winpty) by `pacman -S winpty` in `MSYS2`.
  * `Git Bash` should have winpty installed, no need to install it manually.
  * Add `winpty` before `trzsz`, e.g.: `winpty trzsz ssh x.x.x.x`.

* The `/usr/bin/ssh` in [MSYS2](https://www.msys2.org/) and [Cygwin](https://www.cygwin.com/) is not supported yet, use the [OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) instead.
  * In `MSYS2`, e.g.: `winpty trzsz /c/Windows/System32/OpenSSH/ssh.exe x.x.x.x`.
  * In `Cygwin`, e.g.: `trzsz "C:\Windows\System32\OpenSSH\ssh.exe" x.x.x.x`.

**Comment by lonnywong** [comment]
Try https://github.com/trzsz/trzsz-ssh
