### ISSUE TITLE
distrobox管理下的archlinux容器内，无法使用trzsz

### ISSUE THREAD

**Issue by pmzgit** [trzsz/trzsz-go#26]
# 本地环境
os：deepin20.8（加入内测）
kernel：6.1.12
DE：dde v20
terminal：deepin terminal + fish shell
tmux：3.3a
tmux 配置方案：https://github.com/gpakosz/.tmux
安装方式：github-release下编译好的trzsz-go的可执行文件，已经配置在本地和远程的 `/usr/local/bin` 下
# 总体情况说明
我使用的本地环境比较复杂（远程服务器是普通的linux服务器），在常规的linux 桌面发行版下，安装[distrobox](https://github.com/89luca89/distrobox)和podman容器管理工具，而tmux和trzsz-go都是安装在distrobox和podman 管理下的archlinux容器里（rootless模式）具体使用场景如下：

## 远程：
远程服务器是普通的linux服务器

## 本地：
本地在deepin v20.8 linux桌面发行版上，先后配置安装：podman（rootless模式）;distrobox(一款将其他linux发行版以容器的方式和宿主机整合在一起的工具);pull 并启动 archlinux容器; 在容器里配置tmux/fish/trzsz-go等环境
```sh
# 启动 archlinux容器
distrobox create -i archlinux:latest -n arch-v1 -H /home/pmz/arch-v1 --additional-flags "--pids-limit -1" -v
# 进入容器，并在容器里配置tmux/fish/trzsz-go等环境
distrobox-enter  -n arch-dev -v
# 在容器里启动tmux并使用trzsz-go ssh远程服务器(前提：已将github-release下编译好的trzsz-go的可执行文件，已经配置在本地和远程的 `/usr/local/bin` 下)
trzsz ssh root@n110
# 试图上传文件，此时终端报错
trz 
```
## 终端截图
![image](https://user-images.githubusercontent.com/11833302/232401418-e731d483-41b7-4be5-b186-9f3c61a1ee68.png)

跟踪日志已通过邮件发送到[lonnywong@qq.com](mailto:lonnywong@qq.com)

之前的issue也是我提的https://github.com/trzsz/trzsz-go/issues/16 ，在最后的时候也提到了这个问题，供参考

# 期望目标
之前本地和远程都是在普通的linux 环境下使用，完全没问题，一直再用后来，发现了distrobox神器，经过一段时间的使用，发现完全满足我的需求，结合deepin桌面和archlinux的软件生态的双方优点，一起使用取长补短。但是很可惜不能结合trzsz-go处理文件传输，目前只能用scp凑活用，希望大佬有时间排查一下，有需要补充的日志/信息什么的我再提交

**Comment by lonnywong** [comment]
我看你的截图，是 zenity 报错了，这个是用来打开本地文件选择窗口的。

先确认下，你想上传的文件，是在 distrobox 里面，还是在外面？

**Comment by lonnywong** [comment]
```
trzsz distrobox-enter  -n arch-dev -v
ssh root@n110
tmux
trz
```

```
tmux
trzsz distrobox-enter  -n arch-dev -v
ssh root@n110
trz
```

看起来，只支持这两种，其他都不支持。

**Comment by lonnywong** [comment]
容器内是没有界面的，zenity 打不开也正常？

如果 https://github.com/trzsz/trzsz-go/issues/26#issuecomment-1512318529 这两种都不能满足你的需求，那暂时我也没想到更好的办法了。

**Comment by pmzgit** [comment]
> ```
> trzsz distrobox-enter  -n arch-dev -v
> ssh root@n110
> tmux
> trz
> ```
好吧，这种方式可能不太符合我的需求，这种方式需要远程服务器上也要安装tmux，但是某些服务器网络限制无法安装。
> ```
> tmux
> trzsz distrobox-enter  -n arch-dev -v
> ssh root@n110
> trz
> ```
> 
> 看起来，只支持这两种，其他都不支持。

目前这种方式亲测可用，而且调用的是deepin的文管(但是如果仍然是使用宿主机（deepin）上的tmux（由于基于debian10,tmux版本太老了），而不是容器内tmux的话，就不需要再进入容器再连远程，直接在宿主机上tmux里使用 `trzsz ssh root@n110` 就行了呗)。总之感谢提出了可用方案。

## but！！！
很奇怪，根据您提供的思路，我突然想到，我能不能使用以下这种（前提是宿主机卸载安装的tmux），最符合我的需求：
```sh
trzsz distrobox-enter  -n arch-dev -v
tmux
ssh root@n110
trz
```
试了一下，发现偶尔能够成功，大部分失败(tsz 都失败了)，看下面的截图，有上传成功的，而且调用的是deepin的文管，而不是zenity窗口。



![image](https://user-images.githubusercontent.com/11833302/233054212-5bd186bd-fc49-4de2-8a4e-9772c4174515.png)

**Comment by pmzgit** [comment]
> 容器内是没有界面的，zenity 打不开也正常？

不是的，据我对distrobox的了解，它是利用了xorg的client/server机制，容器内是xorg 客户端程序，窗口绘制是在宿主机（也就是容器外的）xserver上，所以宿主机上有xorg就可以，类似ssh 的 xforward（xwindow 转发）机制。所以distrobox容器里也可以打开带有窗口的程序，只不过我主要使用的是cli程序。

> 如果 [#26 (comment)](https://github.com/trzsz/trzsz-go/issues/26#issuecomment-1512318529) 这两种都不能满足你的需求，那暂时我也没想到更好的办法了。

嗯嗯，目前先这样吧，您说的第二种方案也是可以用的。再次感谢，大佬的优秀开源项目

**Comment by lonnywong** [comment]
```
trzsz distrobox-enter  -n arch-dev -v
tmux
ssh root@n110
trz
```
这种是属于在中间安装 tmux ，trzsz 是不支持的。

你可以试试静态编译一个 tmux 二进制，放到远程去用，并不一定是要安装。

**Comment by lonnywong** [comment]
@pmzgit 新版本支持 tmux 在中间运行的场景，应该能满足你的需求。

现在还没正式发布，你可以自己用 go 1.20 编译一个试试。

最终用法大概会是这样的（ 注意 trzsz 出现了两次，在 tmux 之后的 trzsz 要加上 `-r` 选项 ）：

```
trzsz distrobox-enter -n arch-dev -v
tmux
trzsz -r ssh root@n110
trz
```

**Comment by lonnywong** [comment]
@pmzgit [v1.1.0](https://github.com/trzsz/trzsz-go/releases) 发布了，不用再自己编译。

**Comment by pmzgit** [comment]
> @pmzgit 新版本支持 tmux 在中间运行的场景，应该能满足你的需求。
> 
> 现在还没正式发布，你可以自己用 go 1.20 编译一个试试。
> 
> 最终用法大概会是这样的（ 注意 trzsz 出现了两次，在 tmux 之后的 trzsz 要加上 `-r` 选项 ）：
> 
> ```
> trzsz distrobox-enter -n arch-dev -v
> tmux
> trzsz -r ssh root@n110
> trz
> ```

# 首先，非常感谢大佬持续更新，能支持这种场景，这周末有空测试了一下，初步使用，还是有一点问题
# 环境
* 本地： deepin v23 beta2 + distrobox（ocr 为 podman rootless模式，distrobox 为最新开发分支，1.4.2.1分支有权限bug） + archlinux容器
* ssh的远程：deepin v20.9
* 本地 deepin v23 beta2；distrobox创建的 archlinux容器内；ssh远程的deepin v20.9，都已经安装配置好trzsz(trzsz -v 命令执行正常)
* 使用场景仍然是：archlinux容器，启动tmux，然后ssh 远程服务器，整体执行命令顺序，遵从以上楼主的回复

# 测试结果如图
![image](https://github.com/trzsz/trzsz-go/assets/11833302/39d009a2-9eb4-45b4-bda1-8a3c8e2c866f)

* 第一次上传文件、下载文件都成功了，但是，上传下载成功后，就不停的弹出deepin的文件管理器，我只能不停的点击取消按钮，大概在10来次之后，才不弹了。但是过了一会还可能会开始弹
* 当我exit退出ssh远程后，也出现，开始弹文件管理器窗口，次数大概10-15次的样子，不停手动点击取消按钮后，恢复正常
# 总结
* 我不知道是不是deepin v23 beta2的bug还是什么，下周我在公司deepinv20试一下，保证ssh双方都是deepinv20
* 大佬还需要日志吗，如果需要，我发一下邮箱

**Comment by lonnywong** [comment]
@pmzgit 感谢反馈。我知道这个问题的原因了，等会我修一下。

当 tmux 运行在远程服务器时，我针对这个不断弹出做了优化的。现在 tmux 运行在中间，`trzsz --relay` 也有同样的问题，我优化一下就好。

**Comment by lonnywong** [comment]
@pmzgit 执行 `trzsz --relay` 那个 `trzsz` 更新一下试试？

安装方法（ 要求 go 1.20 以上 ）：`go install github.com/trzsz/trzsz-go/cmd/trzsz@1e59524`，安装后在 `~/go/bin/` 中。

**Comment by pmzgit** [comment]
> @pmzgit 执行 `trzsz --relay` 那个 `trzsz` 更新一下试试？
> 
> 安装方法（ 要求 go 1.20 以上 ）：`go install github.com/trzsz/trzsz-go/cmd/trzsz@1e59524`，安装后在 `~/go/bin/` 中。

我把 执行trzsz -r 和 ssh远程的trzsz都替换了，（还是只替换trssz -r的？）

* 弹窗没再出现
* 经过反复测试，只有ssh远程后，刚开始第一次操作（trz或tsz）成功，第二次及以后都失败，后续exit退出ssh，再次ssh，第一次操作也是失败，以后也是。只有重启容器，重复操作：tmux -> trzsz -r ssh xxx -> trz或tsz 成功，第二次操作trz或tsz及以后都失败
* 下载失败终端截图
![image](https://github.com/trzsz/trzsz-go/assets/11833302/f8e3b6b9-e22d-4cb1-b141-220c15c3e7ea)

* 上传失败终端截图
![image](https://github.com/trzsz/trzsz-go/assets/11833302/2841a639-6de4-4239-82dd-b81140884efe)


如果大佬后期开发新版本，我这边可以一直测试啊

**Comment by lonnywong** [comment]
@pmzgit 只替换 trzsz -r 的，或者都替换也应该可以才对。
```
tmux

trzsz -r -t ssh xxx

echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
# 你会看到一个日志路径，在容器里的。

trz / tsz

# 出错后
echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
```

把那个日志文件发到我的邮箱 lonnywong@qq.com

**Comment by pmzgit** [comment]
> @pmzgit 只替换 trzsz -r 的，或者都替换也应该可以才对。
> 
> ```
> tmux
> 
> trzsz -r -t ssh xxx
> 
> echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
> # 你会看到一个日志路径，在容器里的。
> 
> trz / tsz
> 
> # 出错后
> echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
> ```
> 
> 把那个日志文件发到我的邮箱 [lonnywong@qq.com](mailto:lonnywong@qq.com)

大佬邮件，已发，请查收

**Comment by pmzgit** [comment]
![image](https://github.com/trzsz/trzsz-go/assets/11833302/97bdc178-30de-49fb-9203-28fc522cd99b)

执行tmux的命令就是直接：tmux 或者ctrl+b+d ，detach tmux后，tmux a -t 0，再进入之前的 tmux session。目前一直是这样

**Comment by pmzgit** [comment]
tmux -u 启动，trz、tsz均报错

![image](https://github.com/trzsz/trzsz-go/assets/11833302/f2dac0c5-6bc5-4c02-8bb1-7678ee375f47)
 

![image](https://github.com/trzsz/trzsz-go/assets/11833302/1317d124-e778-4111-986f-4bc32c25d952)

~~tmux -u -2 启动，trz报错了一次，且是第一次，这个有点奇怪，第一次ssh连远程，试了一下trz报错，但是我又从2号window，第二次、第三次重新ssh远程，再次尝试上传、下载，就不在报错~~

tmux -u -2 启动，经过我多轮的测试，总结发现：如果在tmux的panel里(如第一张图，1号window分了两个panel)，trz、tsz偶尔成功，大部分失败；如果只是在window里ssh远程(不分panel，如二图所示)，基本上trz、tsz都成功


![image](https://github.com/trzsz/trzsz-go/assets/11833302/2e3555e7-0eee-4909-ab30-8544c1f078d5)

![image](https://github.com/trzsz/trzsz-go/assets/11833302/8dfd524c-c308-4971-afab-f5946eea29c1)

**顺着这个思路我，重复试了tmux、 tmux -2 tmux -u，都是不分panel时，正常，分panel时，就报错。所以看来，大佬的修复的版本基本是可用的，只是tmux panel下，上传下载不行，我觉得基本上这样就可以了，所以期待大佬发布正式版，基本上满足我在distrobox管理的容器里使用了，还是要说，十分感谢，（为开源项目做一点自己的贡献，给大佬献上一杯冰咖）**

**Comment by lonnywong** [comment]
@pmzgit 感谢打赏，预计本周末会发一个新版本。

**Comment by pmzgit** [comment]
最近有时间回公司办公，顺便在办公电脑的deepinv20.9上，更新trzsz版本，但发现trz上传失败，显示interupted,具体复现，等假期我再报。

不确定是不是deepin版本的问题，之前在deepinv23上测试的没问题了，等假期我具体确认一下

**Comment by lonnywong** [comment]
@pmzgit 后面确认问题后，再开一个新的 issue ？

**Comment by pmzgit** [comment]
抱歉因为最近比较忙，而且平时都在v20.9下工作，所以目前只能用scp代替文件传输，虽然有带你费劲吧，但是搭配zoxide效率也还行.... 今天多次测了一下，v23上传下载（小文件）没问题（tmux不分panel情况下）。发现的问题：

* 大文件下，tsz会中断（稳定复现），trz正常。

* trzsz 到远程后，终端输入有一些问题，但都是一开始没问题，但是工作一段事件后必现：
    * 按下backspace 键，光标不会回退，反而向右移动（但是实际已经起到删除作用）。之前就发现这种问题，但是感觉问题不大，exit后重新trzsz -r ssh远程，又恢复正常
    
    * 版屏显示。也就是下半屏空白

**Comment by lonnywong** [comment]
1、 tsz 下载的问题，两个 trzsz 都是 1.1.3 版本吧？可以搞点日志发到我邮箱 lonnywong@qq.com
```
trzsz -t distrobox-enter ...
tmux
trzsz -r ssh xxx
echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
# 你会看到一个日志路径，在容器外的。
tsz xxx
# 出错后
echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
```

2、backspace 问题也要搞点日志看看：
```
trzsz distrobox-enter ...
tmux
trzsz -t -r ssh xxx
# 正常使用一段时间，当发现 backspace 有异常后
echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
# 你会看到一个日志路径，在容器内的。

# 输入一些字符，然后按几个 backspace ，复现问题后
echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
```

3、半屏是个 bug ，我周末修一下。

**Comment by lonnywong** [comment]
对了，大文件的日志可能会很大，你可以 tail 最后那一两百行发给我。

**Comment by pmzgit** [comment]
> 两个 trzsz 都是 1.1.3 版本吧

邮件已发，是的，准确讲涉及三个环境，对吧，都是1.1.3（具体邮件附件也有说明）

**Comment by lonnywong** [comment]
> 2、backspace 问题也要搞点日志看看：
> 
> ```
> trzsz distrobox-enter ...
> tmux
> trzsz -t -r ssh xxx
> # 正常使用一段时间，当发现 backspace 有异常后
> echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'
> # 你会看到一个日志路径，在容器内的。
> 
> # 输入一些字符，然后按几个 backspace ，复现问题后
> echo -e '<DISABLE_TRZSZ_TRACE_LOG\x3E'
> ```

这个抓出来的日志不是想要的，你在容器内执行 trzsz 时少了 `-r` 参数？另外，你要注意输出的日志路径是什么，只发送输出的那个日志文件过来，你现把历史的也发过来了，这样我不知哪个有用的，很难分析。

**Comment by lonnywong** [comment]
@pmzgit `trzsz_tail200.log` 那个要多发一些日志过来才行，你的网速很多，最后那 200 行不够。

**Comment by lonnywong** [comment]
关于 backspace 的问题，如果没有使用 `trzsz` 是不是正常的？我这里的 backspace 是正常的，trzsz 也没有特殊处理 backspace 的逻辑，只是纯转发，有可能不是 trzsz 的问题。

**Comment by lonnywong** [comment]
@pmzgit 你有没有在用 https://github.com/gpakosz/.tmux 这个？

在下载大文件之前，先执行一下 `tmux setw status-interval 0` ，然后再  `trzsz -r ssh xxx`，`tsz xxx` 看看？

**Comment by pmzgit** [comment]
> @pmzgit 你有没有在用 https://github.com/gpakosz/.tmux 这个？
> 
> 在下载大文件之前，先执行一下 `tmux setw status-interval 0` ，然后再 `trzsz -r ssh xxx`，`tsz xxx` 看看？

对，一直用的这个。最近比较忙，我这几天抽时间看一下

**Comment by lonnywong** [comment]
新版本 `v1.1.5` 会自动设置 `tmux setw status-interval 0` 了，退出时会重置为原来的值。

**Comment by lonnywong** [comment]
@pmzgit 最新的源代码支持隧道传输了，稳定性和速度都会好很多，有空可以试试。

1、需要使用最新的 https://github.com/trzsz/trzsz-ssh ，在 `0.1.12` 发布前，要从源代码编译，或者：
```
go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
```

2、需要使用最新的 `trz` 和 `tsz`，在 `1.1.6` 发布前，要从源代码编译，或者：
```
go install github.com/trzsz/trzsz-go/cmd/trz@main
go install github.com/trzsz/trzsz-go/cmd/tsz@main
``` 

3、要用隧道传输，就必须要在 docker 内开启 ssh 登录，然后用 tssh 登录到 docker 内，在 docker 内再用 tssh 登录到远程服务器。大概流程是这样的：
```
tssh user@docker
tmux
tssh user@remote
trz / tsz
```

**Comment by pmzgit** [comment]
> 新版本 `v1.1.5` 会自动设置 `tmux setw status-interval 0` 了，退出时会重置为原来的值。

忙。。。大概一周前我替换成trzsz-go 到1.1.5版本，然后到研发环境试用，依然是之前的现场环境及流程，但是上传/下载还是不稳定，大概率出现执行报错，重复弹窗，两大问题

**Comment by pmzgit** [comment]
> @pmzgit 最新的源代码支持隧道传输了，稳定性和速度都会好很多，有空可以试试。
> 
> 1、需要使用最新的 https://github.com/trzsz/trzsz-ssh ，在 `0.1.12` 发布前，要从源代码编译，或者：
> 
> ```
> go install github.com/trzsz/trzsz-ssh/cmd/tssh@main
> ```
> 
> 2、需要使用最新的 `trz` 和 `tsz`，在 `1.1.6` 发布前，要从源代码编译，或者：
> 
> ```
> go install github.com/trzsz/trzsz-go/cmd/trz@main
> go install github.com/trzsz/trzsz-go/cmd/tsz@main
> ```
> 
> 3、要用隧道传输，就必须要在 docker 内开启 ssh 登录，然后用 tssh 登录到 docker 内，在 docker 内再用 tssh 登录到远程服务器。大概流程是这样的：
> 
> ```
> tssh user@docker
> tmux
> tssh user@remote
> trz / tsz
> ```

前段时间从开源中国上看到大佬的新项目tssh,但是我一直手动处理ssh免密登陆，然后借助fish+ shell history 加快ssh的使用，考虑需求不强，所以没进一步研究tssh项目

经上面简单介绍，是说tssh下的trz/tsz,使用的是不同于lrzsz的文件传输协议？那我这周抽时间测试一下看看

因为我是重度命令行用户，所以急需高效率的终端文件传输方案，无论如何还是感谢大佬的开源贡献！！

**Comment by lonnywong** [comment]
```
tssh user@docker
tmux
tssh user@remote
trz / tsz
```
https://github.com/trzsz/trzsz-go/issues/26#issuecomment-1722480127 用 [tssh](https://github.com/trzsz/trzsz-ssh)  可以完美解决。如果有问题，再另外开个 issue ？

**Comment by pmzgit** [comment]
> ```
> tssh user@docker
> tmux
> tssh user@remote
> trz / tsz
> ```
> 
> [#26 (comment)](https://github.com/trzsz/trzsz-go/issues/26#issuecomment-1722480127) 用 [tssh](https://github.com/trzsz/trzsz-ssh) 可以完美解决。如果有问题，再另外开个 issue ？

经 deepin v23 beta2 上测试，完美解决（前提是宿主机上安装zenity），十分感谢大佬！！！
