### ISSUE TITLE
几个问题及优化建议

### ISSUE THREAD

**Issue by xiebruce** [trzsz/trzsz-go#28]
搞好了，我是macOS下的iTerm2，有进度条，比lrzsz好多了
<img width="567" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/03f018ba-9726-44dd-ae61-aab188b9f52d">

### 问题
1、为什么同时写两个语言的版本？因为如果是我写的话，肯定集中精力写好一种语言的，因为对用户来说，无论哪种语言都一样用；
2、go版本似乎无法独立使用，因为`trzsz-iterm2`是python写的，它好像是依赖于python版本的trzsz，我个人喜欢go版，希望go版本自带`trzsz-iterm2`，不要依赖于python版；
3、进度条功能是否由python实现，或者说则python调用iTerm2的api实现？是否一定需要python才能实现进度条而不能用其它语言？
4、为什么叫trzsz，t是什么意思？terminal吗？(没有别的意思，只是单纯好奇为什么是t)？
5、在[trzsz-iterm2文档](https://trzsz.github.io/iterm2)中，`which trzsz-iterm2`找不到`trzsz-iterm2`，我是搜索整个`/usr/local/Cellar/`才找到在以下路径
```
/usr/local/Cellar/trzsz/1.1.2/libexec/bin/trzsz-iterm2
```
我是同时用brew安装了python版本和go版本，不过由于两个都要链接到`/usr/local/bin/`会冲突，所以我先`brew unlink trzsz`，然后再`brew link trzsz-go`，不知道是不是跟这个有关。
6、`-d`指定下载目录完全没必要吧，python和go都可以轻易的获取系统的家目录(不行用`$(whoami)`也能找到家目录)
```bash
 -p text -d '/Users/xxx/Downloads' \1
```
7、目前trz传完后输出是这样的
```
::TRZSZ:TRANSFER:R:1.1.0:8466681564300
Received Xnip2023-05-15_19-07-42.jpg, Xnip2023-05-15_19-09-00.jpg, Xnip2023-05-15_19-14-33.jpg to /root
```
由于文件名长，这样并不好看，不如这样：
```bash
Received 3 files to /root:
- 1. Xnip2023-05-15_19-07-42.jpg
- 2. Xnip2023-05-15_19-09-00.jpg
- 3. Xnip2023-05-15_19-14-33.jpg
```

tsz同理
```
Saved a6cc1b4a6221c34b410b739edcb7eb38 (1).jpg.0, a6cc1b4a6221c34b410b739edcb7eb38 (2).jpg.0, a6cc1b4a6221c34b410b739edcb7eb38 (3).jpg.0 to /Users/xxx/Downloads
```

换成
```bash
Saved 3 files to /Users/xxx/Downloads:
- 1. a6cc1b4a6221c34b410b739edcb7eb38 (1).jpg.0
- 2. a6cc1b4a6221c34b410b739edcb7eb38 (2).jpg.0
- 3. a6cc1b4a6221c34b410b739edcb7eb38 (3).jpg.0
```

**Comment by lonnywong** [comment]
逐一回答一下：
1. 一开始只有 python 版，只支持 iTerm2。后来有很多人提出想支持其他终端，如 electerm 和 tabby 等，于是有了 js 版，顺便支持了浏览器 webshell。也有很多人想要支持原生终端，如 ubuntu 自带那个，一开始没想到解决办法，后来想到了，就有了 go 版。
2. mac 上只需要安装 python 版，不要安装 go 版，服务器上可以安装 go 版，三个版本是互相兼容的。
3. iTerm2 进度条依赖其 python api，用 go 比较麻烦，除非用 zenity 进度条。不过我觉得文本进度条更好。
4. t 与 tmux 有关系，我写 trzsz 的初衷是为了解决 tmux 不兼容 lrzsz 的问题。
5. 因为你同时安装了 trzsz 和 trzsz-go，他们都有相同的 trz 和 tsz 程序，冲突了。自己 brew link 一下就好。
6. -d 指定后，就不用每次下载都弹出对话框了，会直接下载到指定目录。
7. 当文件较多，并且较长时，确实你这样更好。有空可以提个 PR 过来。

**Comment by xiebruce** [comment]
> 逐一回答一下：
> 
> 1. 一开始只有 python 版，只支持 iTerm2。后来有很多人提出想支持其他终端，如 electerm 和 tabby 等，于是有了 js 版，顺便支持了浏览器 webshell。也有很多人想要支持原生终端，如 ubuntu 自带那个，一开始没想到解决办法，后来想到了，就有了 go 版。
> 2. mac 上只需要安装 python 版，不要安装 go 版，服务器上可以安装 go 版，三个版本是互相兼容的。
> 3. iTerm2 进度条依赖其 python api，用 go 比较麻烦，除非用 zenity 进度条。不过我觉得文本进度条更好。
> 4. t 与 tmux 有关系，我写 trzsz 的初衷是为了解决 tmux 不兼容 lrzsz 的问题。
> 5. 因为你同时安装了 trzsz 和 trzsz-go，他们都有相同的 trz 和 tsz 程序，冲突了。自己 brew link 一下就好。
> 6. -d 指定后，就不用每次下载都弹出对话框了，会直接下载到指定目录。
> 7. 当文件较多，并且较长时，确实你这样更好。有空可以提个 PR 过来。

感谢大佬逐一回复，辛苦辛苦，其它都明白了，但是对于第6点，我有点明白了，虽然可以不填而直接在代码中获取Downloads文件夹，但如果这样的话，万一我想弹窗，而不想默认保存到“下载”文件夹，还是得传个参数，也就是无论如何都要传参数(或者写在配置文件中)，所以还不如就直接用指定文件夹这个参数了。

**Comment by lonnywong** [comment]
关于第 6 点，可能也有人想直接下载到其他文件夹，而不是“下载”这一个。

**Comment by xiebruce** [comment]
> 关于第 6 点，可能也有人想直接下载到其他文件夹，而不是“下载”这一个。

确实是的。

**Comment by xiebruce** [comment]
大佬你好，我还有个疑问，不管是lrzsz还是你的trzsz，工作原理都是：

- 1、在服务器端输入命令，比如服务器要接收文件就用 rz/trz，此时它会输出一句比较唯一的字符串，用于被iTerm2的Trigger识别；
- 2、iTerm2识别之后，触发执行对应的脚本，对于rz，它会调用sz对应的脚本来发送文件，而sz发送时，并未指定服务器ip，我很好奇这是通过什么原理来上传的？是通过当前的ssh通道吗？
- 3、而对于你写的这个，无论服务器是trz还是tsz，你客户端都调同一个python脚本，这就让我更加不明白，你是怎么区分服务器那边运行的是trz还是tsz的？
- 4、假设你已经区分出服务器运行的是trz，还是跟第2点一样，不明白本地的程序是如何向服务器发送数据的（毕竟没有指定ip，它怎么就知道要发到哪个服务器？比如我iTerm2可能开了几个tab，同时连接了不同服务器，就很难明白不指定服务器ip是怎么实现传输的🤣）

**Comment by lonnywong** [comment]
1、是这样的。
2、trz / tsz 就是一个普通的控制台程序，有 stdin 和 stdout，你按一下键盘，stdin 就可以读入一个字符，你在程序中 print 一个字符串，终端就能显示出来。trz / tsz 用的就是这个 stdin 和 stdout 传输文件的。上传就相当于按了非常多的键盘，下载就相当于显示了非常多的字符。
3、你仔细看，trz 和 tsz 输出的特殊字符串有一点点不一样的。
4、同2，每个 tab 都有自己的 stdin 和 stdout 。

**Comment by xiebruce** [comment]
“上传就相当于按了非常多的键盘，下载就相当于显示了非常多的字符”，明白了，原来是这样。

果然是不一样的
```
# trz
::TRZSZ:TRANSFER:R:1.1.0:8474374665700

# trz -d
::TRZSZ:TRANSFER:D:1.1.0:8474437510600

# tsz
::TRZSZ:TRANSFER:S:1.1.0:8474379056700

# regexp
:(:TRZSZ:TRANSFER:[SRD]:\d+\.\d+\.\d+:\d+)
```
这下我明白了，这三个都符合正则，所以都会触发自动调用python脚本，而调用的时候是`/usr/local/bin/trzsz-iterm2 -p text \1`这样调用的，最后一个`\1`我昨天配置的时候没明白是什么，现在才知道是正则捕获，把正则括号中捕获的内容传到python脚本中，于是python就可以判断到底是在进行哪种操作了，妙啊👍

**Comment by xiebruce** [comment]
关于拖放上传问题，这是我的配置
<img width="946" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/76f5134a-07dc-4cd4-999f-edbf113acf99">

```
/usr/local/opt/trzsz/libexec/bin/trzsz-iterm2 -p text dragfiles \(filenames)
```

我试了一下：

- 1、拖到已登录服务器的终端界面上，如果拖的是文件夹，它自动在终端执行`trz -d`，如果是文件，自动在终端执行`trz`；
- 2、执行`trz -d`或`trz`会输出对应的一串字符串，然后iTerm2 trigger识别到这个字符串，然后呢，它就弹出选择文件窗口让我选择文件；

这样的话，貌似只用“拖放操作”来自动输入`trz/trz -d`，而后还是要我选择文件上传，并没有直接上传我拖放的文件(夹)，按道理，你的python脚本识别到dragfiles参数后，不应该打开窗口让我选择文件，而是直接上传iTerm2通过`\(filenames)`传进来的文件夹(夹)路径呀。

---

另外有一点不明白的是[这个文档](https://github.com/trzsz/trzsz-go/blob/main/README.md)中，有以下描述
<img width="1088" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/708df483-9d99-4bbd-a176-6b30cc6dd4b3">

我试了通过`trzsz --dragfile ssh x.x.x.x`登录服务器，然后再拖放文件到已登录到服务器的终端界面，它还是弹出让我选择文件。

而且我不太明白为什么需要通过在ssh登录前面加上`trzsz --dragfile`，也许这是其它终端使用的？而对于iTerm2，它本身已经可以通过拖放来自动执行我们预设的命令，且命令后面跟上 dragfiles 表示这是拖放操作，而且`\(filenames)`也把拖放的文件(夹)路径传进来了，所以python脚本那儿完全可以判断出来是拖放操作，直接对传进来的文件(夹)进行上传，而不是弹窗让用户选择要上传什么文件。

**Comment by lonnywong** [comment]
trzsz-go 跟 iTerm2 没有关系，用 iTerm2 的 mac 最好不要安装 trzsz-go ，更没必要执行什么 `trzsz --dragfile ssh` 之类的。

你现在搞的太乱了。

**Comment by lonnywong** [comment]
关于 iTerm2 拖动不能上传的问题，你的 iTerm2 是什么版本？服务器的网络质量怎么样？

你试试将这里的 `20` 和 `0.05` 改大一些，看行不行？

https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-iterm2/trzsz/iterm2/main.py#L292-L304

**Comment by xiebruce** [comment]
我只是一开始不知道所以两个都安装了，但是我用的时候用的就是trzsz呀，你看我在拖放触发执行的脚本那边填的是：
```bash
/usr/local/opt/trzsz/libexec/bin/trzsz-iterm2 -p text dragfiles \(filenames)
```

```bash
> ls -l /usr/local/opt/trzsz
lrwxr-xr-x  1 bruce  admin  21 May 21 17:25 /usr/local/opt/trzsz@ -> ../Cellar/trzsz/1.1.2

> ls -l /usr/local/opt/trzsz/libexec/bin/trzsz-iterm2
-rwxr-xr-x  1 bruce  admin  1019 May 21 17:25 /usr/local/opt/trzsz/libexec/bin/trzsz-iterm2*
```

而且我实际使用的时候并没有用`trzsz --dragfile ssh`，只是看到了，就试试而已，实际使用我就是直接：`ssh user@xx.xx.xx.xx` 这样登录的。

我后来测试了，是iterm的问题，我用的是昨天下载的最新的版本[iTerm2-3_5_20230519-nightly.zip](https://iterm2.com/downloads/nightly/iTerm2-3_5_20230519-nightly.zip)，我又试了[iTerm2-3_5_20230503-nightly.zip](https://iterm2.com/downloads/nightly/iTerm2-3_5_20230503-nightly.zip)，这个就没问题。

然后我又换回当前(2023-05-22)最新版本：[iTerm2-3_5_20230522-nightly.zip](https://iterm2.com/downloads/nightly/iTerm2-3_5_20230522-nightly.zip)，拖放上传同样会弹出让我选择，我按你说的把这里改大了几次，还是不能解决
<img width="838" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/e17793e2-40d6-4848-93f7-687c6af52e09">

发现这个报错
```
Traceback (most recent call last):

  File "/usr/local/Cellar/trzsz/1.1.2/libexec/lib/python3.11/site-packages/trzsz/iterm2/main.py", line 297, in drag_files_to_upload

    trigger_match = re.search(trzsz_trigger_regex, output.decode('ascii'))

                                                   ^^^^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 188: ordinal not in range(128)

```

**Comment by xiebruce** [comment]
现在我换回2023-05-03的还是让我选择文件，算了，暂时不用拖放上传功能了🤣，但是我试过一次成功的，我也不知道是怎么回事了

**Comment by xiebruce** [comment]
> “也有很多人想要支持原生终端，如 ubuntu 自带那个，一开始没想到解决办法，后来想到了，就有了 go 版”

我又有一个不明白的问题：支持Ubuntu原生终端需要go版才可以吗？反正都是识别出那串特殊字符串后调用本地的命令，这命令用go写和用python写，不都是被调用执行么？是不是要弹出选择文件窗口必须用go才能实现，用python无法实现？

问题好像有点多，但确实没明白而又想知道为什么，所以就来问了🤣

**Comment by lonnywong** [comment]
python 应该也能做，但我想支持多平台，特别是 Windows。go 版一个 trzsz.exe 程序会比 python 的安装和使用简单很多。

**Comment by xiebruce** [comment]
> python 应该也能做，但我想支持多平台，特别是 Windows。go 版一个 trzsz.exe 程序会比 python 的安装和使用简单很多。

明白了，这个确实是，go的好处就是单个文件搞定，啥也不依赖，不拖家带口，如果不是iTerm2用的python api，你都可以不用python版了，毕竟trigger调用python命令跟调用go可执行文件是一样的，只不过可执行文件首次使用要允许一下权限。

---

我又想出一个问题：

服务器端要接收文件夹时，需要`trz -d`，那么反过来，客户端也应该要`trz -d`吧？可是，服务器端`tsz`输出的那个字符串中，貌似并不包括它是要“发送文件夹”还是“发送文件”的信息，所以客户端应该是无法区别的吧？无法区别的话，客户端怎么知道要使用`trz`还是`trz -d`来接收呢？

还是说，客户端会统一使用`trz -d`，这样无论文件夹还是文件都可以接收？可是如果这样的话，我感觉这个`-d`就没必要存在的，反正不分文件和文件夹。非要说它存在的一个意义，可能是命令界的传统就是加`-r`(或`-d`)来表示对目录进行操作，有这个`-d`可以让用户确定它确实是可以接收文件夹的。

**Comment by xiebruce** [comment]
我试了，确实是这样的，`trz -d`时，可以单选文件，也可以选目录，而`trz`时就只能单选文件了。

另外你说
> python 应该也能做，但我想支持多平台，特别是 Windows。go 版一个 trzsz.exe 程序会比 python 的安装和使用简单很多。

那是不是说，windows端和Linux端(比如ubuntu) 是只要用到go版，完全不需要python版吗？因为只有go版本的话，好像就跟lrzsz类似，对应terminal的触发器没法直接调用`trz`或`tsz`吧？触发器应该都是调用一个小脚本，然后小脚本收集到上传路径之类的，再去调用`trz`或`tsz`的吧？不知道在windows terminal和ubuntu是不是用小脚本(py或shell)调的go版本`tsz`/`trz`？

**Comment by lonnywong** [comment]
对的，Windows 和 Linux 一般用 go 版就可以了。当然 js 和 py 版也是能用的。
现在这个时间点，go 版领先于 py 和 js 版，支持流水线，速度快不少。
触发器这个只有 iTerm2 支持，其他都不支持。有些终端内置支持 trzsz，如 tabby 和 electerm。对于没有内置支持 trzsz 的，又不像 iTerm2 这样有触发器的，只能用 trzsz-go ，用 trzzz ssh 登录，这样 trzsz 就接管了 ssh 的输入和输出，就可以实现了。
上周末想到了个新办法，写一个支持 trzsz 的 ssh ，见 https://github.com/trzsz/trzsz-ssh ，这样 trzsz ssh 就变成 tssh 就好了。这个的重点是解决了 Windows 中 trzsz ssh 上传慢的问题。

**Comment by xiebruce** [comment]
> “这里面的逻辑是 python 特有的”

呃...我大概看了一下，没看出个所以然来。你说python特有的，是指必须用python写才能实现，其它语言都不行吗？是因为里面调用了iTerm2的python api吗？

---

另外我发现一个问题，我发现我拖放文件到本地，它会自己传给自己了（从“下载”文件夹又传回“下载”文件夹），我感觉应该识别一下我拖的是不是ssh登录后的界面，如果不是，那说明拖的是本地，那就还是返回路径(就像没开启拖放功能一样)。
![drag   drop](https://github.com/trzsz/trzsz-go/assets/13575500/1c96cc82-53d2-4d0a-91b2-15a6bc10dd18)

**Comment by lonnywong** [comment]
这个不好识别

**Comment by lonnywong** [comment]
> 呃...我大概看了一下，没看出个所以然来。你说python特有的，是指必须用python写才能实现，其它语言都不行吗？是因为里面调用了iTerm2的python api吗？

只有 python 版有提供 `trzsz-iterm2` 这个程序，go 版没有，我不认为有必要用 go 再实现一个 `trzsz-iterm2` 程序。

| 语言 \ 程序 | `trz` | `tsz` | `trzsz` | `trzsz-iterm2` |
| ---- | ---- | ---- | ---- | ---- |
| Python| √ | √ | X | √ |
| Go | √ | √ | √ | X |

**Comment by xiebruce** [comment]
> > 呃...我大概看了一下，没看出个所以然来。你说python特有的，是指必须用python写才能实现，其它语言都不行吗？是因为里面调用了iTerm2的python api吗？
> 
> 只有 python 版有提供 `trzsz-iterm2` 这个程序，go 版没有，我不认为有必要用 go 再实现一个 `trzsz-iterm2` 程序。
> 
> 语言 \ 程序	`trz`	`tsz`	`trzsz`	`trzsz-iterm2`
> Python	√	√	X	√
> Go	√	√	√	X

你说的这个我是知道的，我只是想问一下，trzsz-iterm2的功能，是不是一定要python才能实现？还是说其实go也能实现，只是觉得没必要再去重复实现一遍？

**Comment by xiebruce** [comment]
> 这个不好识别。建议你用 go 版，`alias ssh="trzsz -d ssh"`，不要配置 iTerm2，这样不会有这个问题。

明白了，本来觉得拖放功能挺好的，但是用这个就没法用拖放功能了 😂

**Comment by xiebruce** [comment]
我发现我登录服务器后(我走代理登录的服务器)，在服务器上输入命令(还没有按回车)，就是随意输入字符也好，它的回显速度，并没有在本地终端速度快，是不是只要我一输入字符，这个字符就马上被传到了服务器，然后再传回来，最强才显示出来，因此我才感受到有“延迟感”？（因为之前我以为是按回车后，我输入的字符才会被传送到服务器）

**Comment by lonnywong** [comment]
`alias ssh="trzsz -d ssh"` 加了 `-d` 是有拖放功能的。

除了 python api 部分，用 go 都是能实现的。

对的，延迟感跟 ping 的耗时有很大关系。

**Comment by xiebruce** [comment]
> `alias ssh="trzsz -d ssh"` 加了 `-d` 是有拖放功能的。
> 
> 除了 python api 部分，用 go 都是能实现的。
> 
> 对的，延迟感跟 ping 的耗时有很大关系。

啊，原来`trzsz`的`-d`竟然是“dragfile”而不是“directory”，我开始还以为是“directory”呢。我现在理解的是，python版本存在的原因，仅仅是因为你需要用[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能，毕竟你当初写这个的原因就是为了支持[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)，如果不用[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)，也是可以用tmux的，只是它不是跟iTerm2集成而已，这么理解不知道对不对？

**Comment by lonnywong** [comment]
对，是。

**Comment by engcn** [comment]
q

**Comment by lonnywong** [comment]
@xiebruce 第 7 点已实现，可以源码安装最新的试试：
```
go install github.com/trzsz/trzsz-go/cmd/trz@5627712
go install github.com/trzsz/trzsz-go/cmd/tsz@5627712
go install github.com/trzsz/trzsz-go/cmd/trzsz@5627712
```
感谢 @amo996 的贡献。

**Comment by xiebruce** [comment]
> @xiebruce 第 7 点已实现，可以源码安装最新的试试：
> 
> ```
> go install github.com/trzsz/trzsz-go/cmd/trz@5627712
> go install github.com/trzsz/trzsz-go/cmd/tsz@5627712
> go install github.com/trzsz/trzsz-go/cmd/trzsz@5627712
> ```
> 
> 感谢 @amo996 的贡献。

测试是可以了，不过不知道为什么服务器`trz -d`时，本地现在只能选文件夹，不能选文件了，我又切换回之前的版本(1.1.0)，还是这样，没有重启系统测试，其他人可以留意一下是不是跟我一样。

系统：macOS Big Sur 11.5.1 (20G80)

**Comment by lonnywong** [comment]
@xiebruce 我也是只能选目录，不能同时选文件和目录了，还没找到什么原因。

你从 [releases](https://github.com/trzsz/trzsz-go/releases)  那里下载一个以前编译出来的试试？

**Comment by lonnywong** [comment]
@xiebruce 看看是不是 iTerm2 触发器那个可以同时选文件和目录？go 版用的库好像是一直都不支持。

**Comment by yurenchen000** [comment]
> 也有很多人想要支持原生终端，如 ubuntu 自带那个，一开始没想到解决办法，后来想到了，就有了 go
@lonnywong 

I used to think add lrzsz support to vte-based terminals.
After some dig, I recognized it's not easy to implement,
cause vte does not provide an interface to handle stdio streams of the pty.

The idea of ​​relay stdio is very clever.
I have previously made a small tool for openssh session keepalive (from Network changes or outages), 
which is similar to the idea of ​​relaying. (some code piece is generated by gpt)
https://github.com/yurenchen000/ssh-keep

I'm still thinking about having a session retention like tmux that allows the client to exit and re-enter.
//maybe modify openssh, or implement a new ssh server/client.

**Comment by lonnywong** [comment]
@yurenchen000 Try https://github.com/trzsz/trzsz-ssh

**Comment by yurenchen000** [comment]
@lonnywong 
thanks for your reply
I came from here 😹
I'm trying the dragfile upload feature and related code (on ubuntu, terminator / gnome-terminal)

about session restore (from client restart)
no clues found yet
