### ISSUE TITLE
windows terminal下无法对窗口大小做出调整。

### ISSUE THREAD

**Issue by BrightXiaoHan** [trzsz/trzsz-go#29]
使用trzsz ssh xxx登录远程后，如果调整字体或者窗口的大小，终端中的窗口无法实时做出响应和变化。
![image](https://github.com/trzsz/trzsz-go/assets/25839309/a2a2cc42-0238-4163-a148-9d27da1232cb)

**Comment by lonnywong** [comment]
周末我补一下这个逻辑。另外，你可以试试这个新写的 https://github.com/trzsz/trzsz-ssh ，不过功能还在完善中……

**Comment by BrightXiaoHan** [comment]
感谢，非常有用的项目！

**Comment by lonnywong** [comment]
@BrightXiaoHan [v1.1.1](https://github.com/trzsz/trzsz-go/releases/tag/v1.1.1) 已解决，可以安装来试试
```
go install github.com/trzsz/trzsz-go/cmd/trzsz@latest
```

在 Windows Terminal 连接 Linux 服务器的话，建议用 https://github.com/trzsz/trzsz-ssh ，可以解决 trz 上传慢的问题。

另外，放了个收款码出来，感谢大佬的打赏 🍻

**Comment by BrightXiaoHan** [comment]
感谢，我试一下。已donate。

**Comment by lonnywong** [comment]
@BrightXiaoHan 收到开源第一笔赞赏，谢谢老板😍
