### ISSUE TITLE
文件夹的上传和下载支持

### ISSUE THREAD

**Issue by Licoy** [trzsz/trzsz-go#3]
- [ ] 增加文件夹的上传支持
- [ ] 增加文件夹的下载支持

希望能够增加如上两项功能的支持！已star！

**Comment by lonnywong** [comment]
我后面抽空支持。

**Comment by lonnywong** [comment]
@Licoy @man2018 

已支持文件夹上传和下载，加个 `-d` 选项就行，如 `trz -d`，或 `tsz -d xxx`。

同时，也支持拖文件夹上传。

**Comment by Licoy** [comment]
@lonnywong 好！

**Comment by engcn** [comment]
拖拽目录可以;   但弹框选择时，无法选择目录

**Comment by lonnywong** [comment]
是 `trz -d`，要有 `-d` 才能选目录。

**Comment by pengatgstdev** [comment]
trz -d加了; 弹框选择时，无法选择目录, 点击确定后即进入目录, 
![图片](https://user-images.githubusercontent.com/19773374/174507436-9e6aeb5c-e1a2-40af-9cd9-4f0115a8a89c.png)

**Comment by lonnywong** [comment]
> trz -d加了; 弹框选择时，无法选择目录, 点击确定后即进入目录,
> ![图片](https://user-images.githubusercontent.com/19773374/174507436-9e6aeb5c-e1a2-40af-9cd9-4f0115a8a89c.png)

原来是 Linux 上有这个问题，我看看怎么搞。

**Comment by lonnywong** [comment]
> trz -d加了; 弹框选择时，无法选择目录, 点击确定后即进入目录,
> ![图片](https://user-images.githubusercontent.com/19773374/174507436-9e6aeb5c-e1a2-40af-9cd9-4f0115a8a89c.png)

你这截图看着好像不对呀，我的代码中没写 “文件上传”这四个字，不应该会这样显示的。

**Comment by lonnywong** [comment]
`trz` 只能选文件的；
`trz -d` 才可以选文件夹；

**Comment by engcn** [comment]
谢谢，可以了;  trzsz -d 和trz -d, 我傻傻分不清了....  ：)
