### ISSUE TITLE
fedroa 38 下无法正常使用

### ISSUE THREAD

**Issue by 0x5c0f** [trzsz/trzsz-go#30]
原`fedora 33` 升级到`38`后，`gnome-shell` 版本变成了`GNOME Shell 44.1` ,  桌面环境已切换为`X11`，`trzsz-go`目前下载的是最新版本。

目前已测试，通过`tabby`构建的通道传输是正常的，也无报错，直接通过`gnome-shell` 连接后(`trzsz bash` 或者 `trzsz ssh xxx`) ,服务器执行报告以下错误，无法拉起本地资源管理器(tabby可以)： 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/trzsz/svr/send.py", line 73, in main
    action = recv_action()
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 318, in recv_action
    return recv_json('ACT')
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 307, in recv_json
    dic = recv_string(typ, may_has_junk)
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 233, in recv_string
    return decode_buffer(recv_check(typ, may_has_junk)).decode('utf8')
  File "/usr/local/lib/python3.6/site-packages/trzsz/libs/utils.py", line 213, in recv_check
    raise TrzszError(buf, typ)
trzsz.libs.utils.TrzszError: exit status 255: 此选项不可用。请参看 --help 了解所有能用的用法。
```

- `local 
  - `trzsz go 1.1.0`
  - `trz (trzsz) py 1.1.2`
  - `tsz (trzsz) py 1.1.2  `

- `server`
  - `trz (trzsz) py 1.1.2`
  - `tsz (trzsz) py 1.1.2`

然后服务器的`trzsz`是通过 `pip3`安装的，实际测试了用`trzsz-go`里面的也一样报错

**Comment by xiebruce** [comment]
你可以认为python版本只是为了支持macOS iTerm2的[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能用的，其它(除tabby, eleterm之类的)一律使用trzsz-go，理论上应该不会有问题，[这篇文章](https://www.xiebruce.top/1864.html)写的非常详细了！

**Comment by lonnywong** [comment]
> 你可以认为python版本只是为了支持macOS iTerm2的[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能用的，其它(除tabby, eleterm之类的)一律使用trzsz-go，理论上应该不会有问题，所以你服务器不应该安装python版本，[这篇文章](https://www.xiebruce.top/1864.html)写的非常详细了！

@xiebruce 这文章写的很好。有几点我补充下：
1、上传和下载大文件，其实也是可以的，理论上没有上限，看网络质量。后面有空，可能还会加个断点续传的能力。
2、electerm 和 tabby 也是基于 electron 的。trzsz.js 的还有一个特点是支持浏览器，即 webshell 那些，和 ttyd 等。
3、服务器端可以安装 py 、js 和 go 的任意一种版本，是完全兼容的。
4、服务器安装的是 trzsz ，你写成 lrzsz ，应该是字母写错了。
5、你的网页是不能复制的，Regular Expression 也多了个表情符号。

**Comment by xiebruce** [comment]
> > 你可以认为python版本只是为了支持macOS iTerm2的[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能用的，其它(除tabby, eleterm之类的)一律使用trzsz-go，理论上应该不会有问题，所以你服务器不应该安装python版本，[这篇文章](https://www.xiebruce.top/1864.html)写的非常详细了！
> 
> @xiebruce 这文章写的很好。有几点我补充下：
> 1、上传和下载大文件，其实也是可以的，理论上没有上限，看网络质量。后面有空，可能还会加个断点续传的能力。
> 2、electerm 和 tabby 也是基于 electron 的。trzsz.js 的还有一个特点是支持浏览器，即 webshell 那些，和 ttyd 等。
> 3、服务器端可以安装 py 、js 和 go 的任意一种版本，是完全兼容的。
> 4、服务器安装的是 trzsz ，你写成 lrzsz ，应该是字母写错了。
> 5、你的网页是不能复制的，Regular Expression 也多了个表情符号。

1、好的，已去除相关的说法；
2、明白，已修改；
3、明白，已修改；
4、确实错写成lrzsz了，已修改；
5、确实不能复制，因为我用js+css双重禁用复制了，因为之前发现有网站盗我文章(是不说明出处那种，随意盗用)。
      Regular Expression 你那个符号是`:(`这就是一个emoji符号，所以被解析了，我现在加上反引号变成行内代码就没事儿了。

**Comment by xiebruce** [comment]
> > 
> 
> @lonnywong 这个日志文件的位置在那儿呢，好像没有看到日志文件产生

`trzsz -t ssh x.x.x.x`登录服务器后，在服务器上执行`echo -e '<ENABLE_TRZSZ_TRACE_LOG\x3E'`它会输出一个路径，如下所示
<img width="571" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/ce076460-04cf-4391-b76c-dc3b7caeedc4">

神奇之处在于，该路径虽然是在服务器上显示，但其实是本地电脑路径，所以你不应该在服务器上找这个文件，那是找不到的，你应该去你本地电脑上找，你看，在本地真有这文件
<img width="834" alt="image" src="https://github.com/trzsz/trzsz-go/assets/13575500/0c926a0b-80a8-4e55-b450-40505a31781b">

**Comment by lonnywong** [comment]
> > 
> 
> @lonnywong 这个日志文件的位置在那儿呢，好像没有看到日志文件产生

会显示出来的，如果没有显示出来，是没有加 `-t` 选项？要 `trzsz -t ssh xxx` 登录。

**Comment by xiebruce** [comment]
> > 看上去，日志是base64 encode了的，是吧？
> 
> 对，是先压缩，然后 base64，这样能看到所有不可见字符是什么。
> 
> 你可以用这段 python 解码来看：https://github.com/trzsz/trzsz/blob/a7d65b1729d5fa3ac604386f818f21c9d901e681/trzsz-libs/trzsz/libs/utils.py#L195-L199

感觉不太对呀，如果你先压缩，再base64，那解码的时候，不是应该先解base64，再解压缩吗？但是你这个代码却是先解压缩
```python
def decode_buffer(buf):
    try:
        return zlib.decompress(base64.b64decode(buf))
    except (TypeError, zlib.error) as e:
        raise TrzszError(buf, str(e))
```

**Comment by lonnywong** [comment]
这个代码是先 base64 解码，再解压缩。

**Comment by xiebruce** [comment]
> 这个代码是先 base64 解码，再解压缩。

啊....可能我现在有点迷糊，明明是先解base64，我为什么看成先解压缩...

**Comment by engcn** [comment]
> 你可以认为python版本只是为了支持macOS iTerm2的[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能用的，其它(除tabby, eleterm之类的)一律使用trzsz-go，理论上应该不会有问题，所以你服务器不应该安装python版本，[这篇文章](https://www.xiebruce.top/1864.html)写的非常详细了！

![image](https://github.com/trzsz/trzsz-go/assets/26758766/4f8e14f1-3296-4d55-9f04-d9a6d0fa9d33)
@xiebruce 主要优点不是这3个，而是解决这俩痛点：
1.支持tmux中使用;
2.不依赖于终端;

**Comment by xiebruce** [comment]
> > 你可以认为python版本只是为了支持macOS iTerm2的[iTerm2 tmux Integration](https://iterm2.com/documentation-tmux-integration.html)功能用的，其它(除tabby, eleterm之类的)一律使用trzsz-go，理论上应该不会有问题，所以你服务器不应该安装python版本，[这篇文章](https://www.xiebruce.top/1864.html)写的非常详细了！
> 
> ![image](https://user-images.githubusercontent.com/26758766/240660711-4f8e14f1-3296-4d55-9f04-d9a6d0fa9d33.png) @xiebruce 主要优点不是这3个，而是解决这俩痛点： 1.支持tmux中使用; 2.不依赖于终端;

感谢提醒，tmux我加上，不过不依赖于终端，跟我第3点说的差不多吧？不依赖的意思，就是在什么终端都能用，而不依赖于iTerm2的触发器，也不依赖于那些内置rz/sz功能的终端，是这意思吧？

**Comment by engcn** [comment]
差不多吧，go版trzsz接管了ssh的输出，相当于处理触发操作了。
1和2是锦上添花，3和4是雪中送碳;

**Comment by xiebruce** [comment]
> 差不多吧，go版trzsz接管了ssh的输出，相当于处理触发操作了。 1和2是锦上添花，3和4是雪中送碳;

由于我不用tmux，并且我用的是iterm2，所以我对3和4没啥感觉，1和2对我来说才是重要的，特别是1(上传进度条)，没有进度条只能靠猜，不知道啥时候传完，难受的要死，当然也是因为我服务器比较慢吧(我走了代理连接的)，如果很快传完，对进度条的需求倒不是那么明显。

**Comment by engcn** [comment]
@xiebruce  嗯， 文章访问有点慢，是部署在国外了吗？

**Comment by xiebruce** [comment]
> @xiebruce 嗯， 文章访问有点慢，是部署在国外了吗？

对的，不过慢的主要原因应该是加载google慢(我对接了google adsense)，如果你能上google，那应该不会太慢，网站接的cf cdn，也许是cf时常抽风吧，如果你用代理的话，把域名加到代理的路由里，让它走代理，应该会快一点，因为静态页面缓存、nginx缓存、redis缓存都加了，它再慢我也没办法了，wordpress搭的，界面样式自己稍微改过。

**Comment by lonnywong** [comment]
@0x5c0f [v1.1.1](https://github.com/trzsz/trzsz-go/releases/tag/v1.1.1) 应该解决了。
