### ISSUE TITLE
No speed for uploading.

### ISSUE THREAD

**Issue by srdfjy** [trzsz/trzsz-go#37]
Hi，thank you very much for providing this tool. I use iTerm2 to log in to the jump server and then to the target server. I've noticed that uploading files using trz is very slow and there is no speed.

My Mac has an M2 chip, and the speed with tsz is not a problem.

![image](https://github.com/trzsz/trzsz-go/assets/66103286/7794ec05-0bfa-4726-a4ec-820564cee85e)

**Comment by lonnywong** [comment]
Try https://github.com/trzsz/trzsz-ssh , compile `tssh` and `trz` from the latest source code.
