### ISSUE TITLE
windows的xshell可以用吗? 

### ISSUE THREAD

**Issue by 189er** [trzsz/trzsz-go#38]
xshell 7

**Comment by 189er** [comment]
果然需要客户端支持的,劝退了

**Comment by lonnywong** [comment]
xshell 打开一个本地终端，然后用 https://github.com/trzsz/trzsz-ssh 登录服务器，就可以。

**Comment by 189er** [comment]
tar -xzvf /tmp/trzsz_1.1.5_linux_x86_64.tar.gz ;

cp trzsz_1.1.5_linux_x86_64/trz /bin/rz  ;
cp trzsz_1.1.5_linux_x86_64/tsz /bin/sz ;
cp trzsz_1.1.5_linux_x86_64/trzsz /bin/;


这样也不支持xhell

**Comment by 189er** [comment]
> xshell 打开一个本地终端，然后用 https://github.com/trzsz/trzsz-ssh 登录服务器，就可以。

得打字输入命令,我用xshell就是因为双击就能打开连接,而且能记住密码 ,打字输入命令不够优雅

**Comment by lonnywong** [comment]
> > xshell 打开一个本地终端，然后用 https://github.com/trzsz/trzsz-ssh 登录服务器，就可以。
> 
> 得打字输入命令,我用xshell就是因为双击就能打开连接,而且能记住密码 ,打字输入命令不够优雅

https://github.com/trzsz/trzsz-ssh 也支持记住密码的，只运行 tssh 也可以用键盘选择要登录的服务器。

xshell 不是开源的，你可以建议他们公司支持 trzsz 。

**Comment by engcn** [comment]
> 得打字输入命令,我用xshell就是因为双击就能打开连接,而且能记住密码 ,打字输入命令不够优雅

Xshell有后门，而且使用记住密码的方式登录很不安全；命令行中使用ssh公钥登录或者证书方式登录安全性更高，而且也能免密码登录呀。
如果有很多主机，在xshell的弹框中需要上下滚动先找到主机再双击登录，或者为主机分组建立目录，找起来一层层进目录， 浪费时间不说，更不优雅；如果用ssh命令，只需要输入5~6个字符就可以登录(即使有几百台主机)；而用tssh就更方便了，这还不够优雅？

另外，所有的主机和复杂的ssh命令操作，都可以定义到一个配置文件中，修改或者迁移都很方便；命令行远远优于图形画的ssh工具，Xshell没有存在的意义。
