### ISSUE TITLE
Crash on Termux (aarch64)

### ISSUE THREAD

**Issue by marco-trovato** [trzsz/trzsz-go#39]
On **Termux** from Android with an ARM 64 phone, the program instantly crash.

**Steps to reproduce:**
1. wget "trzsz_1.1.5_linux_aarch64.tar.gz"
2. tar zxvf trzsz_1.1.5_linux_aarch64.tar.gz
3. Run: `./trzsz-go ssh remotemachine`
4. Crash
5. Be sad :(

Any suggestions? Let me know if a dump of the output may help

**Comment by romanovj** [comment]
build yourself

cd ~
go install github.com/trzsz/trzsz-go/cmd/...@latest
go/bin/trzsz -v

**Comment by lonnywong** [comment]
@marco-trovato tar zxvf trzsz_1.1.5_linux_aarch64.tar.gz

**Comment by marco-trovato** [comment]
> @marco-trovato tar zxvf trzsz_1.1.5_linux_aarch64.tar.gz

You're right @lonnywong, I fixed the steps.

---

@romanovj:

Thank you for your help, I compiled from the sources and it didn't crash. Improvement!
But weirdly it still didn't work when I tried to download a file in the remote machine with **tsz**.

It's really odd because it works on all other Linux/Windows machines, and I don't know how to troubleshoot it.

**Comment by lonnywong** [comment]
@marco-trovato You may need to install `zenity` first.

**Comment by marco-trovato** [comment]
It seems that `pkg search zenity` returns nothing on Termux.

The behaviour is so weird because with **tsz** the filetransfer seems to start, but it immediately freezes until you press CTRL-C. I guess you're right and it could be the destination folder dialogs.

**Comment by lonnywong** [comment]
Without `zenity`, you can add a config file `~/.trzsz.conf`:
```
DefaultDownloadPath = /path/to/save/files/
```
The `tsz` should work, but `trz` can't work without `zenity`.

**Comment by marco-trovato** [comment]
Ok I created the config file as you suggested, but it wasn't enough: before connecting I also had to wrap the trzsz command around the bash, i.e. by running:
`trzsz fish`

And then it worked! Thank you for your help!!!

**Comment by lonnywong** [comment]
If you want to make `trz` work, you can build a script named `zenity`, call the `termux api` in it, let the user choose some files, and then output the absolute path of the files to stdout, just like the `zenity` does in other Linux.

I'm not familiar with the `termux api`, don't know how to pop up a file picker dialog.

**Comment by marco-trovato** [comment]
In theory the **zenity** alternative for Termux is termux-dialog (install it by typing: `pkg install termux-api`).

And it returns the value in JSON, so you have to parse it with **jq** like this:

name=$(termux-dialog text -t "Please enter a name" | jq '.text')
echo "$name"

But this is too much assle to understand how to make a workaround: if things gets this complicated I rather use **scp** instead.

**Comment by romanovj** [comment]
pkg install x11-repo
pkg install zenity

but you will need to start Graphical Environment
