### ISSUE TITLE
Is armhf supported?

### ISSUE THREAD

**Issue by ragazenta** [trzsz/trzsz-go#40]
Hi, I see no `armhf` build in the Releases page, is that architecture supported?

Thanks.

**Comment by lonnywong** [comment]
Yes, it’s supported. You can build it from source.

**Comment by lonnywong** [comment]
Do you have arm v6 & v7 environment for testing? I'll accept PR as long as it's tested. Thanks.

**Comment by ragazenta** [comment]
Yes, I have Raspberry Pi Zero (armv6) and Pi 4B (armv7 and arm64). What kind of testing do you need?

**Comment by lonnywong** [comment]
As long as `trz`, `tsz` and `trzsz` can upload and download files, it will be fine.

**Comment by ragazenta** [comment]
I've tested on Raspberry Pi Zero (armv6) and Pi 4b (armv6 & armv7), upload and download work fine.

- [x] `trz`
- [x] `tsz` something
- [x] `trzsz` ssh and bash 
- [x] `ttyd -t enableTrzsz=true`

**Comment by lonnywong** [comment]
@ragazenta Thanks. Could you make a PR for this?
