### ISSUE TITLE
something wrong with processbar

### ISSUE THREAD

**Issue by baicker** [trzsz/trzsz-go#44]
mac m1 pro, iterm2, tmux<BR>
<img width="731" alt="image" src="https://github.com/trzsz/trzsz-go/assets/7483947/e27de554-693a-4125-8865-c5d57f1f560e">

**Comment by lonnywong** [comment]
Check https://trzsz.github.io/iterm2

The action of iTerm2 trigger should be `Run Silent Coprocess...`.

**Comment by baicker** [comment]
thanks, well done.
