### ISSUE TITLE
Zmodem有点疑惑

### ISSUE THREAD

**Issue by zundaren** [trzsz/trzsz-go#47]
一般都是服务器上安装lrzsz，客户端适配协议，但是文档说需要在客户端（ 本地电脑 ）上安装 lrzsz，就很奇怪。
虽然rzsz传输有些功能无法和trzsz兼容，能否以trzsz的实现的功能为接口层，lrzsz适配trzsz，功能没有的直接忽略，这样是不是合理一点，这样服务器不用安装trzsz，客户端装一个trzsz。

**Comment by lonnywong** [comment]
trzsz-go 没有完整实现 zmodem 协议，没那么多时间搞。

现在的做法是，在本地拉起 rz / sz 子进程，让它们与服务器的 rz / sz 进程进行通讯，trzsz-go 在这中间扮演数据转发的角色。

具体实现你可以看看：https://github.com/trzsz/trzsz-go/blob/main/trzsz/zmodem.go

**Comment by zundaren** [comment]
> trzsz-go 没有完整实现 zmodem 协议，没那么多时间搞。
> 
> 现在的做法是，在本地拉起 rz / sz 子进程，让它们与服务器的 rz / sz 进程进行通讯，trzsz-go 在这中间扮演数据转发的角色。
> 
> 具体实现你可以看看：https://github.com/trzsz/trzsz-go/blob/main/trzsz/zmodem.go

好滴，我研究下
