### ISSUE TITLE
Not working on Synology NAS DS220+

### ISSUE THREAD

**Issue by guoqiao** [trzsz/trzsz-go#5]
## NAS info: 

- Model: Intel(R) Celeron(R) J4025 CPU @ 2.00GHz
- Instruction Set: 64-bit
- ref: https://www.intel.com/content/www/us/en/products/sku/197307/intel-celeron-processor-j4025-4m-cache-up-to-2-90-ghz/specifications.html

## Local machine info:

- CPU: Intel 10900K
- OS: Ubuntu 20.04 LTS
- Terminal app: Terminator
- Shell: zsh

Steps to reproduce:

- download zip from release, copy the bin files to `~/bin/` dir on both local machine and nas.
- ensure `trz|tsz|trzsz` are in `$PATH` and available via `which` on both sides
- on local machine, in terminal, run `trzsz -d ssh nas`
- on local machine, open file explorer, drag a file to terminal
- nothing happens

Maybe it will he helpful to provide a debug option.

**Comment by lonnywong** [comment]
Thanks for your feedback.
Without `trzsz`, open the Terminal, drag files into it, what happens?
Does the Terminal show the absolute paths?
Can you take a screenshot of the absolute paths?

**Comment by guoqiao** [comment]
@lonnywong  I see,  the issue is caused by my terminal app, Terminator.
When drag and drop a file to it,  the file path is not there.
There is a bug for it: https://github.com/gnome-terminator/terminator/pull/54

When I try with builtin terminal,  it's working fine.

Thank you for the tip, I will close this issue.
