### ISSUE TITLE
是否考虑支持一下 kylin server 版本操作系统？

### ISSUE THREAD

**Issue by netcore-jroger** [trzsz/trzsz-go#50]
如题，是否考虑支持一下 kylin server 版本操作系统？

**Comment by lonnywong** [comment]
用对应 CPU 架构的 go 直接编译，应该直接就支持的。

**Comment by netcore-jroger** [comment]
就是 intel 的 CPU

**Comment by lonnywong** [comment]
https://github.com/trzsz/trzsz-go/releases/download/v1.1.7/trzsz_1.1.7_linux_x86_64.tar.gz
看看这个解压之后能不能用？

**Comment by netcore-jroger** [comment]
明天我验证一下给你回复

**Comment by netcore-jroger** [comment]
![image](https://github.com/trzsz/trzsz-go/assets/3223890/5138d92a-e131-4f6d-861b-2fb4000fb718)
卡在这儿弹不出选择文件的窗口，和我提这个 issue 之前一样的效果

**Comment by lonnywong** [comment]
你是怎么登录服务器的？用 https://github.com/trzsz/trzsz-ssh 还是 `trzsz ssh xxx` ?

**Comment by netcore-jroger** [comment]
哎呀，忘记了。得用 tssh。我是用的ssh。抱歉

**Comment by netcore-jroger** [comment]
用 tssh 可以了。
