### ISSUE TITLE
Support for mosh?

### ISSUE THREAD

**Issue by markshep** [trzsz/trzsz-go#51]
I love this program - thanks for writing it!

I've successfully used trzsz-go with both SSH sessions and interactive [AWS SSM Sessions](https://docs.aws.amazon.com/cli/latest/reference/ssm/start-session.html) but it doesn't work with [mosh](https://github.com/mobile-shell/mosh) sessions.  I know it's quite a different protocol as it uses UDP rather than TCP and has predictive modelling of the screen state so I guess it wouldn't be trivial, but is it even possible?

**Comment by lonnywong** [comment]
The `mosh-server` rewrites the stdout output. It controls the output of the entire screen, causing the data transmitted by trzsz to be lost.

You might want to try  https://github.com/trzsz/trzsz-ssh

**Comment by lonnywong** [comment]
@markshep How about making another `mosh` with `trzsz` support and port forwarding?

Based on [tssh](https://github.com/trzsz/trzsz-ssh):
- Make a new `tssh-server` program to replace `mosh-server`.
- Make `tssh --udp` to replace `mosh` ( Support enabling `--udp` by default in ssh configuration ).
- `tssh` and `tssh-server` use the udp protocol to communicate like `mosh`.

**Comment by lonnywong** [comment]
Now, [tssh](https://github.com/trzsz/trzsz-ssh) supports `--udp` mode like `mosh`. The [tsshd](https://github.com/trzsz/tsshd) works like `mosh-server`.

Please check https://github.com/trzsz/trzsz-ssh/blob/main/README.en.md#udp-mode for more details.

**Comment by lonnywong** [comment]
[`tssh --udp`](https://github.com/trzsz/trzsz-ssh) and [tsshd](https://github.com/trzsz/tsshd) are released.
