### ISSUE TITLE
上传后可执行文件执行权限没了

### ISSUE THREAD

**Issue by iFurySt** [trzsz/trzsz-go#53]
是否可以支持一下上传后的文件权限问题？目前遇到的上传的文件执行权限会丢失，每次都要手动再给权限，极大不便。如果担心安全性之类的问题，可以考虑加个参数？

**Comment by lonnywong** [comment]
你用的是什么版本？最新版是会保留权限的。

**Comment by iFurySt** [comment]
```
Server: go 1.1.7
Client: py 1.1.5
```
需要升级一下client到1.1.7?

**Comment by lonnywong** [comment]
客户端用 go 1.1.7 以上，或者用 https://github.com/trzsz/trzsz-ssh ( 0.1.19 以上 ）。

**Comment by iFurySt** [comment]
trzsz-iterm2是不是只能用py client？

**Comment by lonnywong** [comment]
`trzsz-iterm2` 是只有 python 版，现在还不支持文件权限。

但是 iTerm2 不是只能用 `trzsz-iterm2` 的，还可以用 go 版的 trzsz ，或者用 https://github.com/trzsz/trzsz-ssh  。

**Comment by iFurySt** [comment]
```
Reg Exp:
:(:TRZSZ:TRANSFER:[SRD]:\d+\.\d+\.\d+:\d+)
Parameters:
/opt/homebrew/bin/trzsz text -d '/path/to/xx' \1
```
![image](https://github.com/trzsz/trzsz-go/assets/16201837/9bc87d9b-dbde-460e-9b34-96dbb10c33e1)

不知道如果使用trzsz-go的话，iterm2里如何配置呢？这样设置后，上传显示依然会调用trzsz-iterm2，不确定是哪里直接调用了trzsz-iterm2

**Comment by lonnywong** [comment]
> 不知道如果使用trzsz-go的话，iterm2里如何配置呢？这样设置后，上传显示依然会调用trzsz-iterm2，不确定是哪里直接调用了trzsz-iterm2

不需要在 iTerm2 中配置任何东西，只要安装相应的软件，并用相应的方法登录服务器。以下两种是等价的，任选一种即可：

1、使用 [trzsz-ssh ( tssh )](https://github.com/trzsz/trzsz-ssh)，安装 `brew install trzsz-ssh`，登录服务器要用 `tssh xxx` （ `xxx` 替换成服务器 ）。

2、使用 [trzsz-go](https://github.com/trzsz/trzsz-go)，安装 `brew install trzsz-go`，登录服务器要用 `trzsz ssh xxx` （ `xxx` 替换成服务器 ）。
