### ISSUE TITLE
Windows terminal 不支持

### ISSUE THREAD

**Issue by snsnsjsn** [trzsz/trzsz-go#54]
root~# which trzsz
/usr/bin/trzsz
root~# which trzsz-iterm2
/usr/bin/which: no trzsz-iterm2 in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
root~# trz
::TRZSZ:TRANSFER:R:1.1.7:1653262608500:36693
#fail:eJzyzCtJLSoqLShJTQEEAAD//xsTBJc=
Interrupted
root~# tsz test.txt
::TRZSZ:TRANSFER:S:1.1.7:1653293314900:43532

既不能上传弹出选择窗口，也不能下载

![image](https://github.com/trzsz/trzsz-go/assets/11435527/c303d507-4b85-48f3-863b-438537c6b301)

**Comment by lonnywong** [comment]
是 Windows Terminal 还是 iTerm2 ?

**Comment by lonnywong** [comment]
1、本地安装  https://github.com/trzsz/trzsz-ssh
2、服务器安装 https://github.com/trzsz/trzsz-go
3、用 tssh 登录服务器，使用 trz 上传，使用 tsz 下载。
