### ISSUE TITLE
Not working on Synology NAS DS918+

### ISSUE THREAD

**Issue by ferocknew** [trzsz/trzsz-go#6]
```bash
# admin @ DS918x86 in ~/tools [10:28:28] 
$             
bracketed-paste-magic:zle:47: not enough arguments for -U
```

客户端，macos（zsh）
服务端，群晖（zsh）

**Comment by lonnywong** [comment]
拖文件进去时提示这个？

如果在服务端输入命令 `trz -v` 是显示什么？

如果在服务端输入命令 `trz` 会不会弹出对话框？没有话框的话，显示什么？

**Comment by ferocknew** [comment]
> 拖文件进去时提示这个？
> 
> 如果在服务端输入命令 `trz -v` 是显示什么？
> 
> 如果在服务端输入命令 `trz` 会不会弹出对话框？没有弹出对话框的话，显示什么？

```bash
# admin @ DS918x86 in ~/tools [10:28:39] 
$ trz -v
trz (trzsz) go 0.1.6
```

会弹出对话框，显示

```bash
# admin @ DS918x86 in ~/tools [12:55:00] 
$ trz
::TRZSZGO:TRANSFER:R:0.1.6:0
```

**Comment by lonnywong** [comment]
拖文件进去时提示 `not enough arguments for -U` ？

如果不用 `trzsz` ，直接使用 `ssh` 登录，拖文件进去，能看到显示文件的绝对路径不？

**Comment by ferocknew** [comment]
> 拖文件进去时提示 `not enough arguments for -U` ？
> 
> 如果不用 `trzsz` ，直接使用 `ssh` 登录，拖文件进去，能看到显示文件的绝对路径不？

<img width="447" alt="image" src="https://user-images.githubusercontent.com/2178683/173218485-263f5f0e-e7ad-4913-b269-906cf7213e4e.png">

**Comment by lonnywong** [comment]
在  mac 端看起来没啥问题。用 `trzsz -d ssh` 登录，然后拖文件进去，是下面这样的结果？不应该啊，方便截个图吗？

```
# admin @ DS918x86 in ~/tools [10:28:28] 
$             
bracketed-paste-magic:zle:47: not enough arguments for -U
```

**Comment by ferocknew** [comment]
> 在 mac 端看起来没啥问题。用 `trzsz -d ssh` 登录，然后拖文件进去，是下面这样的结果？不应该啊，方便截个图吗？
> 
> ```
> # admin @ DS918x86 in ~/tools [10:28:28] 
> $             
> bracketed-paste-magic:zle:47: not enough arguments for -U
> ```

<img width="486" alt="image" src="https://user-images.githubusercontent.com/2178683/173219724-5653b266-125b-40f9-8159-5de51e87a176.png">

**Comment by lonnywong** [comment]
感谢反馈，我从 mac 上 ssh 到远程的 linux 是正常的，刚发现在本地 trzsz zsh 好像是有问题，我先查一下。

**Comment by lonnywong** [comment]
> 
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/2178683/173218485-263f5f0e-e7ad-4913-b269-906cf7213e4e.png">

远程服务器是不是也是 macOS 来的？我看路径下的白色底，和 macOS 本地的显示很像。

**Comment by ferocknew** [comment]
> > <img alt="image" width="447" src="https://user-images.githubusercontent.com/2178683/173218485-263f5f0e-e7ad-4913-b269-906cf7213e4e.png">
> 
> 远程服务器是不是也是 macOS 来的？我看路径下的白色底，和 macOS 本地的显示很像。

不是，只是也用了zsh 同样的 themes

**Comment by lonnywong** [comment]
我提交了一个修复版本，方便编译来试试不？

```sh
brew install go
git clone https://github.com/trzsz/trzsz-go.git
cd trzsz-go
make
```

用 go1.18 来编译的，编译后，程序在 trzsz-go/bin 中，只要用 bin 下那个 `trzsz` 就可以了，远程服务器上的 `trz` 和 `tsz` 不用改（ 编译出来 mac 的版本也不能放到 linux 上去用 ）。

**Comment by lonnywong** [comment]
如果还是不行的话，最新的版本（ 需要自己编译 ）加了调试日志的功能。

1、用 `trzsz -d -t ssh` 登录。
2、登录后在服务器上执行 `echo -e '\tENABLE_TRZSZ_TRACE_LOG\t'` 会开启日志，此时会输出日志的路径（ 在本地电脑上 ）。
3、在服务器上执行 `echo -e '\tDISABLE_TRZSZ_TRACE_LOG\t'` 可以关闭日志，会再次输出日志的路径。

可以将日志发到我的邮箱 lonnywong@qq.com

**Comment by ferocknew** [comment]
brew install go 


。。。。还在下载，国内源一些安装报404

**Comment by lonnywong** [comment]
或者我编译一个发给你？给一下邮箱就行。

**Comment by ferocknew** [comment]
> 
我给你发邮件了

**Comment by lonnywong** [comment]
发了两次都当垃圾邮件退回了，试试微云分享可以下载不？

https://share.weiyun.com/peQKq3ZL

**Comment by ferocknew** [comment]
> 发了两次都当垃圾邮件退回了，试试微云分享可以下载不？
> 
> https://share.weiyun.com/peQKq3ZL

可以了，改了啥？

**Comment by lonnywong** [comment]
是指可以上传了？

有关的应该是这几行代码：

https://github.com/trzsz/trzsz-go/commit/c50128faa4ab46713067d1cae314714c002d15e2#diff-b7334cc923169eed6566440ad4c181622dc01147f48de8a56cef4e7f74f93e00R81

**Comment by ferocknew** [comment]
果然缺了一个参数

**Comment by ferocknew** [comment]
可以close 了

**Comment by lonnywong** [comment]
> 
> @lonnywong 我不懂go, 问下，除了上述打印日志的方式调试，能通过打断点的方式调试SSH子进程的输入输出吗？或者像gdb命令行那样调试？

可以的，https://github.com/go-delve/delve 这个就挺好用的，用着也像 gdb。我自己调试时也会用它。

我加日志是为了方便以后，当有用户说在他的环境上有问题时，可以打印日志发出来。

**Comment by engcn** [comment]
哦哦，谢谢
