### ISSUE TITLE
传送大文件（5G+）的时候，网络断了，Ctrl+C 没反应，程序自己也不会断开。

### ISSUE THREAD

**Issue by ferocknew** [trzsz/trzsz-go#7]
如题

**Comment by lonnywong** [comment]
有个默认 100 秒超时的，100 秒后也没反应？

如果不传文件，只是 trzsz ssh 登录了，然后网络断开了，会是什么样的表现？

**Comment by ferocknew** [comment]
100秒，没留意

就是窗口卡死。
常规用 ssh 如果断网会有提示。

刚刚试了一下，估计到了 100秒
提示

```bash
# admin @ DS918x86 in ~ [10:23:42] 
$ Shared connection to 10.0.0.204 closed.
```

**Comment by ferocknew** [comment]
建议这个时间短一点

**Comment by lonnywong** [comment]
感谢，我考虑新版本改成 10 秒左右。

**Comment by ferocknew** [comment]
确认了，100秒可以断开。
100秒内卡死。

timeout 短点体验会好点。

**Comment by ferocknew** [comment]
确认了，100秒可以断开。
100秒内卡死。

timeout 短点体验会好点。

**Comment by ferocknew** [comment]
另，建议： 提示一下是否覆盖文件，否则默认覆盖太不安全了

**Comment by lonnywong** [comment]
> 另，建议： 提示一下是否覆盖文件，否则默认覆盖太不安全了

默认不会覆盖的，会在后面加个 `.1`，`.2` 之类的后缀，需要手工自己改一下文件名。

只有 `trz -y` 和 `tsz -y xxx` 才会覆盖存在的文件。

另外，拖文件上传时，是不会启用覆盖的功能的。

**Comment by ferocknew** [comment]
> > 另，建议： 提示一下是否覆盖文件，否则默认覆盖太不安全了
> 
> 默认不会覆盖的，会在后面加个 `.1`，`.2` 之类的后缀，需要手工自己改一下文件名。
> 
> 只有 `trz -y` 和 `tsz -y xxx` 才会覆盖存在的文件。
> 
> 另外，拖文件上传时，是不会启用覆盖的功能的。

看到了，的确是这样的。只是，是从0 开始



<img width="422" alt="image" src="https://user-images.githubusercontent.com/2178683/173272551-d1937d11-780c-40d8-901a-15f71a72cac4.png">

**Comment by lonnywong** [comment]
> 确认了，100秒可以断开。 100秒内卡死。
> 
> timeout 短点体验会好点。

v0.1.7 版本，超时时间已改为 10 秒。
